name: snapshot
description: A library that can be used to implement data classes and simplifies conversion of JSON to data classes
version: 0.2.6
homepage: https://github.com/appsup-dart/snapshot

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  intl: '>=0.17.0 <0.20.0'
  meta: ^1.3.0
  collection: ^1.15.0
  quiver: ^3.0.0
  rxdart: ^0.27.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
