name: snapshot
description: A library that can be used to implement data classes and simplifies conversion of JSON to data classes
version: 0.1.0-dev.3
homepage: https://github.com/appsup-dart/snapshot

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  json_patch: ^2.0.0
  intl: ^0.16.1
  meta: ^1.1.8
  collection: ^1.14.0
  quiver: ^2.1.0
  rxdart: ^0.24.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
