name: snapshot
description: A library that can be used to implement data classes and simplifies conversion of JSON to data classes
version: 0.2.6+3
homepage: https://github.com/appsup-dart/snapshot
repository: https://github.com/appsup-dart/snapshot

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  intl: '>=0.17.0 <0.21.0'
  meta: ^1.3.0
  collection: ^1.15.0
  quiver: ^3.0.0
  rxdart: '>=0.27.0 <0.29.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
  melos: ^7.0.0


melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1


  